Update GitHub Actions workflows to disable credential persistence and validate PR number input

diff --git a/.github/workflows/preview.yml b/.github/workflows/preview.yml
--- a/.github/workflows/preview.yml
+++ b/.github/workflows/preview.yml
@@ -25,13 +25,18 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+        with:
+          persist-credentials: false
 
       - name: Set environment variables
         run: |
           if [[ "${{ github.event.number }}" ]]; then
             echo "PR_NUMBER=${{ github.event.number }}" >> $GITHUB_ENV
-          else
+          elif [[ "${{ github.event.inputs.pr_number }}" =~ ^[0-9]+$ ]]; then
             echo "PR_NUMBER=${{ github.event.inputs.pr_number }}" >> $GITHUB_ENV
+          else
+            echo "Invalid PR number!" >&2
+            exit 1
           fi
           echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
           echo "MASTODON_ACCESS_TOKEN=${{ secrets.MASTODON_ACCESS_TOKEN }}" >> $GITHUB_ENV
